version: '3'
services:
  opensearch-test1: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-test1
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
      - ./opensearch-test1/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./opensearch-test1/opensearch-test1.crt:/usr/share/opensearch/config/opensearch-test1.crt
      - ./opensearch-test1/opensearch-test1.key:/usr/share/opensearch/config/opensearch-test1.key
      - ./opensearch-ca.crt:/usr/share/opensearch/config/opensearch-ca.crt
      - ./opensearch-security/:/usr/share/opensearch/config/opensearch-security/
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network

  # For running any additional setup commands
  opensearch-test-setup:
    image: opensearchproject/opensearch:latest
    depends_on:
      - opensearch-test1
    restart: "no"
    networks:
      - opensearch-net
    volumes:
      - ./opensearch-ca.crt:/usr/share/opensearch/config/opensearch-ca.crt
      - ./opensearch-security/:/usr/share/opensearch/config/opensearch-security/
    entrypoint: [ "bash", "-c", "sleep 15 && \
      /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh \
      -cd /usr/share/opensearch/config/opensearch-security \
      -cacert /usr/share/opensearch/config/opensearch-ca.crt \
      -cert /usr/share/opensearch/config/opensearch-security/test-admin.crt \
      -key /usr/share/opensearch/config/opensearch-security/test-admin.key \
      -icl -nhnv \
      -p 9200 -h opensearch-test1.local"
    ]

  opensearch-dashboards-test1:
    image: opensearchproject/opensearch-dashboards:latest # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    container_name: opensearch-dashboards-test1
    depends_on:
      - opensearch-test1
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    volumes:
      - ./opensearch-dashboards-test1/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
      - ./opensearch-dashboards-test1/opensearch-dashboards-test1.crt:/usr/share/opensearch-dashboards/opensearch-dashboards-test1.crt
      - ./opensearch-dashboards-test1/opensearch-dashboards-test1.key:/usr/share/opensearch-dashboards/opensearch-dashboards-test1.key
      - ./opensearch-ca.crt:/usr/share/opensearch-dashboards/opensearch-ca.crt
    networks:
      - opensearch-net

  opensearch-dataprepper-test1:
    image: opensearchproject/data-prepper:latest
    container_name: opensearch-dataprepper-test1
    depends_on:
      - opensearch-test1
    ports:
      - 4900:4900
      - 2021:2021
    expose:
      - "4900"
      - "2021"
    volumes:
      # Certificates
      - ./opensearch-ca.crt:/usr/share/data-prepper/opensearch-ca.crt
      - ./opensearch-dataprepper-test1/certs/opensearch-dataprepper-test1.crt:/usr/share/data-prepper/certs/opensearch-dataprepper-test1.crt
      - ./opensearch-dataprepper-test1/certs/opensearch-dataprepper-test1.key:/usr/share/data-prepper/certs/opensearch-dataprepper-test1.key
      - ./opensearch-dataprepper-test1/certs/opensearch-dataprepper-test1.pfx:/usr/share/data-prepper/certs/opensearch-dataprepper-test1.pfx

      # Config files
      - ./opensearch-dataprepper-test1/config/data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
      - ./opensearch-dataprepper-test1/pipelines/:/usr/share/data-prepper/pipelines/
    networks:
      - opensearch-net

volumes:
  opensearch-data1:

networks:
  opensearch-net:
